name: visual-regression-test
on:
  pull_request:
    branches:
      - develop
defaults:
  run:
    shell: bash

jobs:
  # developブランチのscreenshotsを確認する
  check_expected_screenshots:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: volta-cli/action@v4
      - uses: actions/checkout@v3
        with:
          ref: develop
          # VRTで正確に比較するためにシャロークローンを無効化する
          # シャロークローンは、--depth=<数値>オプションを付けて、最新のコミットから指定した数だけを取得する機能です。
          fetch-depth: 0
      
      # VRTを行ったキャッシュがあるかどうか調べる
      - name: restore cached expected screenshots
        id: screenshots_cache
        uses: ./.github/actions/cache-screenshots
        with:
          lookup-only: 'true'

      # node_modulesのキャッシュのあるかどうか調べて、なかったらinstallする
      - name: restore cached node_modules
        if: ${{ steps.screenshots_cache.outputs.cache-hit != 'true' }}
        uses: ./.github/actions/cache-node-modules

      # storybookのbuildデータのキャッシュがあるかどうか調べる
      - name: cache storybook build result
        if: ${{ steps.screenshots_cache.outputs.cache-hit != 'true' }}
        id: storybook_result_cache
        uses: ./.github/actions/cache-storybook-build-result

      # VRTを行ったキャッシュもstorybookのbuildデータのキャッシュもなかったらstorybookをbuildする
      - name: storybook build
        if: ${{ steps.screenshots_cache.outputs.cache-hit != 'true' && steps.storybook_result_cache.outputs.cache-hit != 'true'}}
        run: npm run storybook:build
        # build scriptに渡す環境変数
        env:
          NEXT_IS_TEST: 'true'

  # developブランチのscreenshotsを撮る
  take_expected_screenshots:
    needs: check_expected_screenshots
    runs-on: ubuntu-latest
    timeout-minutes: 30
    # タスクを4つに分割し、並列で実行することで全体の実行時間を大幅に短縮
    strategy:
      matrix:
        shard: [1/4, 2/4, 3/4, 4/4]
    
    steps:
      - uses: volta-cli/action@v4
      - uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      # VRTを行ったキャッシュがあるかどうか調べる
      - name: restore cached expected screenshots
        id: screenshots_cache
        uses: ./.github/actions/cache-screenshots
        with:
          lookup-only: 'false'

      # node_modulesのキャッシュのあるかどうか調べて、なかったらinstallする
      - name: restore cached node_modules
        if: ${{ steps.screenshots_cache.outputs.cache-hit != 'true' }}
        uses: ./.github/actions/cache-node-modules

      # storybookのbuildデータのキャッシュがあるかどうか調べる
      - name: cache storybook build result
        if: ${{ steps.screenshots_cache.outputs.cache-hit != 'true' }}
        id: storybook_result_cache
        uses: ./.github/actions/cache-storybook-build-result

      # screenshotsを撮る準備
      - name: prepare for screenshots
        if: ${{ steps.screenshots_cache.outputs.cache-hit != 'true' }}
        uses: ./.github/actions/prepare-screenshots

      # screenshotsを撮る
      - name: take screenshots
        if: ${{ steps.screenshots_cache.outputs.cache-hit != 'true' }}
        run: npm run vrt:snapshot -- --shard=${{ matrix.shard }}

      # artifactにscreenshotsをアップロードする
      - name: upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: expected-screenshots-${{ strategy.job-index }}
          path: __screenshots__
          retention-days: 1

  # developブランチのartifactに分割してアップロードされているスクリーンショットをひとつにする
  merge_expected_screenshots:
    needs: take_expected_screenshots
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Download all sharded expected artifacts
        uses: actions/download-artifact@v4
        with:
          # ワイルドカードで全てダウンロード
          pattern: expected-screenshots-*
          path: all_expected_screenshots/
          # 1つのディレクトリにマージする
          merge-multiple: true

      - name: Upload merged expected artifact
        uses: actions/upload-artifact@v4
        with:
          # 最終的なアーティファクト名
          name: expected-screenshots
          path: all_expected_screenshots/
          retention-days: 1

  # featureブランチのscreenshotsを確認する
  check_actual_screenshots:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: volta-cli/action@v4
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Detached HEAD状態を解消し、明確な名前を持つブランチに確実に切り替える
      - name: workaround for detached HEAD
        # ${GITHUB_HEAD_REF}は、プルリクエストの元ブランチの参照情報（例: refs/heads/feature/new-design）を格納している環境変数
        # #refs/heads/は、その文字列の先頭からrefs/heads/という部分を取り除くシェルの機能
        run: |
          git checkout ${GITHUB_HEAD_REF#refs/heads/} || git checkout -b ${GITHUB_HEAD_REF#refs/heads/} && git pull

      # VRTを行ったかどうか調べる
      - name: restore cached actual screenshots
        id: screenshots_cache
        uses: ./.github/actions/cache-screenshots
        with:
          lookup-only: 'true'
      
      # node_modulesのキャッシュがあるかどうか調べる。なかったらinstallする
      - name: restore cached node_modules
        if: ${{ steps.screenshots_cache.outputs.cache-hit != 'true' }}
        uses: ./.github/actions/cache-node-modules

      # storybookのbuildデータのキャッシュがあるかどうか調べる
      - name: cache storybook build result
        if: ${{ steps.screenshots_cache.outputs.cache-hit != 'true' }}
        id: storybook_result_cache
        uses: ./.github/actions/cache-storybook-build-result

      # VRTのキャッシュもstorybookのbuildデータキャッシュもなかったらstorybookをbuildする
      - name: storybook build
        if: ${{ steps.screenshots_cache.outputs.cache-hit != 'true' && steps.storybook_result_cache.outputs.cache-hit != 'true' }}
        run: npm run storybook:build
        env:
          NEXT_IS_TEST: 'true'

  # featureブランチのscreenshotsを撮る
  take_actual_screenshots:
    needs: check_actual_screenshots
    runs-on: ubuntu-latest
    timeout-minutes: 30
    # タスクを4つに分割し、並列で実行することで全体の実行時間を大幅に短縮
    strategy:
      matrix:
        shard: [1/4, 2/4, 3/4, 4/4]
    
    steps:
      - uses: volta-cli/action@v4
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Detached HEAD状態を解消し、明確な名前を持つブランチに確実に切り替える
      - name: workaround for detached HEAD
        # ${GITHUB_HEAD_REF}は、プルリクエストの元ブランチの参照情報（例: refs/heads/feature/new-design）を格納している環境変数
        # #refs/heads/は、その文字列の先頭からrefs/heads/という部分を取り除くシェルの機能
        run: |
          git checkout ${GITHUB_HEAD_REF#refs/heads/} || git checkout -b ${GITHUB_HEAD_REF#refs/heads/} && git pull

      # VRTを行ったキャッシュがあるかどうか調べる
      - name: restore cached actual screenshots
        id: screenshots_cache
        uses: ./.github/actions/cache-screenshots
        with:
          lookup-only: 'false'

      # node_modulesのキャッシュのあるかどうか調べて、なかったらinstallする
      - name: restore cached node_modules
        if: ${{ steps.screenshots_cache.outputs.cache-hit != 'true' }}
        uses: ./.github/actions/cache-node-modules

      # storybookのbuildデータのキャッシュがあるかどうか調べる
      - name: cache storybook build result
        if: ${{ steps.screenshots_cache.outputs.cache-hit != 'true' }}
        id: storybook_result_cache
        uses: ./.github/actions/cache-storybook-build-result

      # screenshotsを撮る準備
      - name: prepare for screenshots
        if: ${{ steps.screenshots_cache.outputs.cache-hit != 'true' }}
        uses: ./.github/actions/prepare-screenshots

      # screenshotsを撮る
      - name: take screenshots
        if: ${{ steps.screenshots_cache.outputs.cache-hit != 'true' }}
        run: npm run vrt:snapshot -- --shard=${{ matrix.shard }}

      # artifactにscreenshotsをアップロードする
      - name: upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: actual-screenshots-${{ strategy.job-index }}
          path: __screenshots__
          retention-days: 1

  # featureブランチのartifactに分割してアップロードされているスクリーンショットをひとつにする
  merge_actual_screenshots:
    needs: take_actual_screenshots
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Download all sharded actual artifacts
        uses: actions/download-artifact@v4
        with:
          # ワイルドカードで全てダウンロード
          pattern: actual-screenshots-*
          path: all_actual_screenshots/
          # 1つのディレクトリにマージする
          merge-multiple: true

      - name: Upload merged actual artifact
        uses: actions/upload-artifact@v4
        with:
          # 最終的なアーティファクト名
          name: actual-screenshots
          path: all_actual_screenshots/
          retention-days: 1


  # VRTを行い、レポートをgithub pagesに公開する
  run_reg_suit:
    needs:
      - merge_expected_screenshots
      - merge_actual_screenshots
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: volta-cli/action@v4
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # VRTを行ったキャッシュがあるかどうか調べる
      - name: restore cached expected screenshots
        id: screenshots_cache
        uses: ./.github/actions/cache-screenshots
        with:
          lookup-only: 'false'

      # developブランチのスクリーンショットをartifactからダウンロードする
      - name: download expected screenshots
        if: ${{ steps.screenshots_cache.outputs.cache-hit != 'true' }}
        uses: actions/download-artifact@v4
        with:
          name: expected-screenshots
          path: __screenshots__

      # ダウンロードしたdevelopブランチのスクリーンショットを.reg/expected/に移動する
      - name: set reg-suit expected
        if: ${{ steps.screenshots_cache.outputs.cache-hit != 'true' }}
        run: |
          rm -rf .reg/expected/
          mkdir -p .reg/expected
          mv -f __screenshots__/* .reg/expected
          ls -l .reg/

      # featureブランチのスクリーンショットをartifactからダウンロードする
      - name: download actual screenshots
        uses: actions/download-artifact@v4
        with:
          name: actual-screenshots
          path: __screenshots__

      # node-modulesのキャッシュがあるかどうか調べて、なければinstallする
      - name: restore cached node_modules
        if: ${{ steps.screenshots_cache.outputs.cache-hit != 'true' }}
        uses: ./.github/actions/cache-node-modules

      # Detached HEAD状態を解消し、明確な名前を持つブランチに確実に切り替える
      - name: workaround for detached HEAD
        # ${GITHUB_HEAD_REF}は、プルリクエストの元ブランチの参照情報（例: refs/heads/feature/new-design）を格納している環境変数
        # #refs/heads/は、その文字列の先頭からrefs/heads/という部分を取り除くシェルの機能
        run: |
          git checkout ${GITHUB_HEAD_REF#refs/heads/} || git checkout -b ${GITHUB_HEAD_REF#refs/heads/} && git pull

      # VRTを実行する
      - name: run reg-suit
        run: npm run vrt:run

      # VRTのレポートをgithub pagesに公開する
      - name: deploy report to github page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .reg/
          # 公開先のサブディレクトリを指定する。
          # github.head_refはプルリクエストの元となっているブランチ名（例: feature/new-design）が自動的に入る。
          destination_dir: ${{ github.head_ref }}

      # プルリクエストにボットが投稿した過去のレポートコメントを探す
      - name: find comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: reg-suit report

      # プルリクエスト内に見つけたコメントを更新するか、なければ新規にコメントを作成します。
      - name: upsert comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            reg-suit report
            https://kaori-igawa.github.io/frontend-testing-book_nextjs/${{github.head_ref}}
          edit-mode: replace

